CREATE DATABASE USERS_DB;

CREATE TABLE USERS (
  USER_ID INTEGER PRIMARY KEY,
  USER_NAME VARCHAR(200)
);

INSERT INTO USERS VALUES (1, 'Dariia');
INSERT INTO USERS VALUES (2, 'Alex');

SELECT * FROM USERS;

